import JobPanel from '../JobPanel/JobPanel';
const Experience = () => {
    const jobs = [
        {
            company: "Loopio",
            title: "Senior Software Engineer",
            startDate: "Sep 2022",
            endDate: "Present",
            description: [
                "Collaborated with a team to design and deliver new feature for the platform",
                "Participated in code reviews, testing, and resolving open defects",
                "Developed features for integrations between loopio and various third-party platforms(salesforce, seismic, slack, ...).",
                "Worked on full stack development using React.js, Typescript, Javascript, and PHP"
            ]
        },
        {
            company: "Ritual",
            title: "Backend Engineer",
            startDate: "May 2022",
            endDate: "June 2022",
            description: [
                "Developed for RESTful Spring Boot microservice to be consumed by the Ritual Android Marketplace App",
                "Applied Test-Driven-Development (TDD) with JUnit and Mockito to develop reusable and reliable code",
                "Collaborated with the team in a fast-paced Agile environment to deliver 5 new features and enhancements",
                "Conducted code reviews for new features, and tested and resolved open defects"
            ]
        },
        {
            company: "RBC",
            title: "Senior DevOps Engineer",
            startDate: "March 2019",
            endDate: "March 2020",
            description: [
                "Designed and built an in-house Security Scanning Tool for managing secrets across the RBC Enterprise GitHub. Increased security scanning performance and memory usage by over 3000%",
                "Executed centralized logging for numerous applications using Elastic Stack (Elasticsearch, Filebeat, Logstash, Kibana) for greater security, automated troubleshooting and log simplification",
                "Built Python ETL jobs for a multitude of onsite vendor applications to enable transparency in dashboards, reporting, and cost savings for stakeholders and clients",
                "Created end-to-end Integration test suites (including Rest API testing) using Python and Selenium for better efficiency with increased test coverage",
            ]
        },
        {
            company: "RBC",
            title: "Quality Engineer Analyst",
            startDate: "March 2020",
            endDate: "April 2022",
            description: [
                "Worked with Business and project teams to determine, review and verify test scope",
                "Responsible for quality of functional and non-functional test activities, showing continuous improvement in testing and supporting test automation",
                "Held defect triage meetings",
                "Created an end-to-end test automation suite using best practices (page object model design pattern) and reduced testing efforts from 3 manual testers to 1 test automation developer for a Credit Risk rating application",
                "Using Jenkins to create pipeline scripts for continuous integration and deployment",
                "Created and maintained a Python package for bridging an in-house end-to-end test automation framework with Jenkins for continued reporting",
            ]
        },
        {
            company: "RBC",
            title: "Test Automation Developer",
            startDate: "March 2017",
            endDate: "March 2019",
            description: [
                "created and maintained (over 300) end-to-end test automation suites using in-house test automation framework",
                "Built and maintained a test automation framework to simplify test automation, reduce boilerplate, decrease automation test creation and maintenance time with autogenerated logging, and report creation",
                "Designed a code generator to automate code creation of Python and Selenium UI interactions",
                "Analyzed and validated large sets of data used for migration, analysis and visualization",
                "Developed scripts (Audit Bots) to flag users per compliance standards and policies for GitHub",
                "Developed and designed web service for automation of high traffic support tickets"
            ]
        },
    ];
    return (
        <section id="experience" className="bg-bgPrimary-light dark:bg-bgPrimary-dark h-screen flex flex-col justify-center">
            <div className="p-10 max-w-screen-lg mx-auto">
                <h1 className="text-textPrimary-light dark:text-textPrimary-dark my-5 uppercase text-xl"><span className="text-sm text-textSecondary-light dark:text-textSecondary-dark">02. </span>My Journey</h1>
                <div className="flex flex-col sm:flex-row">
                    <JobPanel jobs={jobs} />
                </div>
            </div>
        </section>
    )
}
export default Experience